from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Literal

Direction = Literal["claude-to-codex", "codex-to-claude", "both"]
Conflict = Literal["skip", "claude", "codex", "newest"]

SKILL_NAME = re.compile(r"^[a-z0-9][a-z0-9-]{0,63}$")
EXCLUDED_DIRS = {".git", "__pycache__", "node_modules"}
EXCLUDED_FILES = {".DS_Store", ".env"}
SECRET_NAMES = re.compile(
    r"(^|[._-])(credentials?|secrets?|tokens?|private[-_]?key)([._-]|$)", re.I
)
COMMAND_MARKER = "<!-- Generated by agent-skill-sync. Edit command.md in this directory. -->"
PROMPT_MARKER = "<!-- Generated by agent-skill-sync from Claude Code. -->"
CODEX_FRONTMATTER_KEYS = {"allowed-tools", "description", "license", "metadata", "name"}


@dataclass(frozen=True)
class Paths:
    claude_skills: Path
    codex_skills: Path
    claude_commands: Path
    state_file: Path
    codex_prompts: Path | None = None

    @classmethod
    def defaults(cls, home: Path | None = None) -> "Paths":
        home = home or Path.home()
        return cls(
            claude_skills=home / ".claude" / "skills",
            codex_skills=home / ".codex" / "skills",
            claude_commands=home / ".claude" / "commands",
            state_file=home / ".config" / "agent-skill-sync" / "state.json",
            codex_prompts=home / ".codex" / "prompts",
        )


@dataclass
class Action:
    kind: str
    name: str
    source: str | None = None
    destination: str | None = None
    detail: str | None = None


@dataclass
class Report:
    actions: list[Action]
    applied: bool

    @property
    def changed(self) -> int:
        return sum(action.kind in {"copy", "update", "command", "prompt"} for action in self.actions)

    @property
    def conflicts(self) -> int:
        return sum(action.kind == "conflict" for action in self.actions)

    def as_dict(self) -> dict:
        return {
            "applied": self.applied,
            "changed": self.changed,
            "conflicts": self.conflicts,
            "actions": [asdict(action) for action in self.actions],
        }


def is_excluded(path: Path) -> bool:
    return (
        any(part in EXCLUDED_DIRS for part in path.parts)
        or path.name in EXCLUDED_FILES
        or bool(SECRET_NAMES.search(path.name))
    )


def skill_dirs(root: Path, include_hidden: bool = False) -> dict[str, Path]:
    if not root.exists():
        return {}
    result: dict[str, Path] = {}
    for entry in sorted(root.iterdir(), key=lambda p: p.name):
        if entry.name.startswith(".") and not include_hidden:
            continue
        if not SKILL_NAME.fullmatch(entry.name):
            continue
        if entry.is_dir() and (entry / "SKILL.md").is_file():
            result[entry.name] = entry
    return result


def command_files(root: Path) -> dict[str, Path]:
    if not root.exists():
        return {}
    return {
        path.stem: path
        for path in sorted(root.glob("*.md"))
        if SKILL_NAME.fullmatch(path.stem) and not is_excluded(path)
    }


def safe_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for current, dirs, names in os.walk(root, followlinks=True):
        current_path = Path(current)
        dirs[:] = [name for name in dirs if not is_excluded(current_path / name)]
        for name in names:
            path = current_path / name
            if not is_excluded(path) and path.is_file():
                files.append(path)
    return sorted(files, key=lambda path: path.relative_to(root).as_posix())


def codex_skill_markdown(content: str) -> str:
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n?", content, re.S)
    if not match:
        return content
    chunks: list[tuple[str, list[str]]] = []
    for line in match.group(1).splitlines():
        key_match = re.match(r"^([A-Za-z0-9_-]+):", line)
        if key_match:
            chunks.append((key_match.group(1), [line]))
        elif chunks:
            chunks[-1][1].append(line)

    output: list[str] = []
    for key, lines in chunks:
        if key not in CODEX_FRONTMATTER_KEYS:
            continue
        if key == "description":
            raw = lines[0].split(":", 1)[1].strip()
            if len(lines) > 1:
                raw = " ".join([raw, *(line.strip() for line in lines[1])]).strip()
            if len(raw) >= 2 and raw[0] == raw[-1] == '"':
                try:
                    raw = json.loads(raw)
                except json.JSONDecodeError:
                    raw = raw[1:-1]
            elif len(raw) >= 2 and raw[0] == raw[-1] == "'":
                raw = raw[1:-1].replace("''", "'")
            raw = raw.replace("<", "").replace(">", "")[:1024]
            output.append(f"description: {json.dumps(raw)}")
        else:
            output.extend(lines)
    body = content[match.end():]
    return "---\n" + "\n".join(output) + "\n---\n\n" + body.lstrip("\n")


def tree_hash(root: Path, codex_compatible: bool = False) -> str:
    digest = hashlib.sha256()
    for path in safe_files(root):
        relative = path.relative_to(root).as_posix()
        digest.update(relative.encode())
        digest.update(b"\0")
        content = path.read_bytes()
        if codex_compatible and relative == "SKILL.md":
            content = codex_skill_markdown(content.decode()).encode()
        digest.update(content)
        digest.update(b"\0")
    return digest.hexdigest()


def copy_skill(source: Path, destination: Path, codex_compatible: bool = False) -> None:
    temporary = destination.with_name(f".{destination.name}.skill-sync-tmp")
    if temporary.exists():
        shutil.rmtree(temporary)
    temporary.mkdir(parents=True)
    for source_file in safe_files(source):
        relative = source_file.relative_to(source)
        target_file = temporary / relative
        target_file.parent.mkdir(parents=True, exist_ok=True)
        if codex_compatible and relative.as_posix() == "SKILL.md":
            target_file.write_text(codex_skill_markdown(source_file.read_text()))
            shutil.copystat(source_file, target_file, follow_symlinks=True)
        else:
            shutil.copy2(source_file, target_file, follow_symlinks=True)
    if destination.exists() or destination.is_symlink():
        if destination.is_dir() and not destination.is_symlink():
            shutil.rmtree(destination)
        else:
            destination.unlink()
    temporary.replace(destination)


def load_state(path: Path) -> dict:
    try:
        data = json.loads(path.read_text())
        return data if data.get("version") == 1 else {"version": 1, "skills": {}}
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {"version": 1, "skills": {}}


def write_state(path: Path, state: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
    temporary.replace(path)


def choose_conflict(
    policy: Conflict, claude: Path, codex: Path
) -> Literal["claude", "codex"] | None:
    if policy in {"claude", "codex"}:
        return policy
    if policy == "newest":
        claude_mtime = max(path.stat().st_mtime_ns for path in safe_files(claude))
        codex_mtime = max(path.stat().st_mtime_ns for path in safe_files(codex))
        return "claude" if claude_mtime >= codex_mtime else "codex"
    return None


def command_description(content: str, name: str) -> str:
    frontmatter = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.S)
    if frontmatter:
        match = re.search(r"^description:\s*[\"']?(.*?)[\"']?\s*$", frontmatter.group(1), re.M)
        if match and match.group(1):
            return match.group(1).replace('"', "'").replace("<", "").replace(">", "")[:900]
    return f"Run the imported Claude Code /{name} command from Codex."


def render_command_skill(name: str, content: str) -> str:
    description = command_description(content, name)
    return (
        "---\n"
        f"name: claude-command-{name}\n"
        f'description: "{description} Use when the user invokes or asks for /{name}."\n'
        "---\n\n"
        f"{COMMAND_MARKER}\n\n"
        f"# Claude command: /{name}\n\n"
        "Read `command.md` in this directory and execute its instructions. "
        "Treat any text supplied with this skill as the command arguments, replacing "
        "Claude's `$ARGUMENTS` placeholder where it appears.\n"
    )


def render_codex_prompt(name: str, content: str, assets: list[Path]) -> str:
    description = command_description(content, name)
    hint_match = re.search(r"^argument-hint:\s*(.*?)\s*$", content, re.M)
    frontmatter = re.match(r"^---\s*\n.*?\n---\s*\n?", content, re.S)
    body = content[frontmatter.end():] if frontmatter else content
    for asset in assets:
        codex_asset = f"~/.codex/skills/claude-command-{name}/{asset.name}"
        body = body.replace(f"~/.claude/commands/{asset.name}", codex_asset)
        body = re.sub(
            rf"(?<![/\w.-]){re.escape(asset.name)}(?![\w.-])",
            codex_asset,
            body,
        )
    metadata = ["---", f"description: {json.dumps(description)}"]
    if hint_match:
        metadata.append(f"argument-hint: {json.dumps(hint_match.group(1))}")
    metadata.extend(["---", "", PROMPT_MARKER, ""])
    return "\n".join(metadata) + body.lstrip("\n")


def command_assets(source: Path, content: str) -> list[Path]:
    return [
        candidate
        for candidate in sorted(source.parent.iterdir(), key=lambda path: path.name)
        if candidate != source
        and candidate.is_file()
        and not is_excluded(candidate)
        and candidate.name in content
    ]


def sync_commands(paths: Paths, apply: bool, actions: list[Action]) -> None:
    prompts_root = paths.codex_prompts or paths.codex_skills.parent / "prompts"
    for name, source in command_files(paths.claude_commands).items():
        destination = paths.codex_skills / f"claude-command-{name}"
        original = source.read_text()
        rendered = render_command_skill(name, original)
        assets = command_assets(source, original)
        current_original = destination / "command.md"
        current_skill = destination / "SKILL.md"
        skill_current = (
            current_original.is_file()
            and current_skill.is_file()
            and current_original.read_text() == original
            and current_skill.read_text() == rendered
            and all(
                (destination / asset.name).is_file()
                and (destination / asset.name).read_bytes() == asset.read_bytes()
                for asset in assets
            )
        )
        if skill_current:
            actions.append(Action("same", f"command:{name}"))
        elif destination.exists() and not (
            current_skill.is_file() and COMMAND_MARKER in current_skill.read_text()
        ):
            actions.append(Action("conflict", f"command:{name}", detail="target is not managed"))
        else:
            actions.append(Action("command", name, str(source), str(destination)))
            if apply:
                destination.mkdir(parents=True, exist_ok=True)
                current_original.write_text(original)
                current_skill.write_text(rendered)
                for asset in assets:
                    shutil.copy2(asset, destination / asset.name)

        prompt = prompts_root / f"{name}.md"
        prompt_content = render_codex_prompt(name, original, assets)
        if prompt.is_file() and prompt.read_text() == prompt_content:
            actions.append(Action("same", f"prompt:{name}"))
        elif prompt.exists() and PROMPT_MARKER not in prompt.read_text():
            actions.append(Action("conflict", f"prompt:{name}", detail="target is not managed"))
        else:
            actions.append(Action("prompt", name, str(source), str(prompt)))
            if apply:
                prompts_root.mkdir(parents=True, exist_ok=True)
                prompt.write_text(prompt_content)


def sync(
    paths: Paths,
    direction: Direction = "both",
    conflict: Conflict = "skip",
    include_commands: bool = True,
    apply: bool = False,
    exclude: set[str] | None = None,
) -> Report:
    claude = skill_dirs(paths.claude_skills)
    codex = skill_dirs(paths.codex_skills)
    state = load_state(paths.state_file)
    previous = state.setdefault("skills", {})
    actions: list[Action] = []

    exclude = exclude or set()
    for name in sorted((set(claude) | set(codex)) - exclude):
        claude_path = claude.get(name)
        codex_path = codex.get(name)
        old = previous.get(name, {})

        if claude_path and not codex_path:
            if direction in {"claude-to-codex", "both"}:
                target = paths.codex_skills / name
                actions.append(Action("copy", name, str(claude_path), str(target)))
                if apply:
                    copy_skill(claude_path, target, codex_compatible=True)
                    codex_path = target
            else:
                actions.append(Action("only-claude", name))
        elif codex_path and not claude_path:
            if direction in {"codex-to-claude", "both"}:
                target = paths.claude_skills / name
                actions.append(Action("copy", name, str(codex_path), str(target)))
                if apply:
                    copy_skill(codex_path, target)
                    claude_path = target
            else:
                actions.append(Action("only-codex", name))
        elif claude_path and codex_path:
            claude_hash = tree_hash(claude_path)
            codex_hash = tree_hash(codex_path)
            if tree_hash(claude_path, codex_compatible=True) == codex_hash:
                actions.append(Action("same", name))
            else:
                winner: Literal["claude", "codex"] | None = None
                if direction == "both" and old.get("claude") == claude_hash and old.get("codex") != codex_hash:
                    winner = "codex"
                elif direction == "both" and old.get("codex") == codex_hash and old.get("claude") != claude_hash:
                    winner = "claude"
                else:
                    winner = choose_conflict(conflict, claude_path, codex_path)

                allowed = (
                    direction == "both"
                    or (direction == "claude-to-codex" and winner == "claude")
                    or (direction == "codex-to-claude" and winner == "codex")
                )
                if winner is not None and not allowed:
                    winner = None

                if winner is None:
                    actions.append(Action("conflict", name, detail="both copies differ"))
                else:
                    source = claude_path if winner == "claude" else codex_path
                    destination = codex_path if winner == "claude" else claude_path
                    actions.append(Action("update", name, str(source), str(destination), winner))
                    if apply:
                        copy_skill(source, destination, codex_compatible=winner == "claude")

        if apply:
            final_claude = paths.claude_skills / name
            final_codex = paths.codex_skills / name
            if (final_claude / "SKILL.md").is_file() and (final_codex / "SKILL.md").is_file():
                previous[name] = {
                    "claude": tree_hash(final_claude),
                    "codex": tree_hash(final_codex),
                }

    if include_commands and direction in {"claude-to-codex", "both"}:
        sync_commands(paths, apply, actions)
    if apply:
        write_state(paths.state_file, state)
    return Report(actions=actions, applied=apply)
